spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:forum
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cache:
    caffeine:
      spec: maximumSize=100, expireAfterWrite=10m
    type: caffeine

#    http://localhost:8080/h2-console
  h2:
    console:
      enabled: true
